name: firebase deploy

on:
  push:
    branches:
      - master

env:
  cache-version: v1

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ env.cache-version }}-${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-node-

      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      # - name: test
      #   env:
      #     TZ: 'Asia/Tokyo'
      #   run: yarn test:cov

      # - uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: 'coverage/lcov.info'

      # Storybookをgithub pagesにホスティング
      - name: build Storybook
        run: yarn build:sb

      - name: deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
